// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_pnlSolar1;
extern lv_obj_t * ui_ImgEvcc;
extern lv_obj_t * ui_barHomeBattery;
extern lv_obj_t * ui_ImgBattery;
extern lv_obj_t * ui_barBatteryPower;
extern lv_obj_t * ui_spinLadung;
extern lv_obj_t * ui_ImgPlug;
extern lv_obj_t * ui_lblLadepunkt;
extern lv_obj_t * ui_lblLadeleistung;
extern lv_obj_t * ui_txtLadeleistung;
extern lv_obj_t * ui_pnlCarSoc;
extern lv_obj_t * ui_txtLadestand;
extern lv_obj_t * ui_lblAuto;
extern lv_obj_t * ui_barCarSoc;
extern void ui_event_sliderSocLimit(lv_event_t * e);
extern lv_obj_t * ui_sliderSocLimit;
extern lv_obj_t * ui_lblReichweite;
extern lv_obj_t * ui_txtReichweite;
extern lv_obj_t * ui_lblRestzeit;
extern lv_obj_t * ui_txtRestzeit;
extern lv_obj_t * ui_lblLadeenergie;
extern lv_obj_t * ui_txtLadeenergie;
extern lv_obj_t * ui_lblLadelimit;
extern lv_obj_t * ui_txtLadelimit;
extern void ui_event_BtnModusPv(lv_event_t * e);
extern lv_obj_t * ui_BtnModusPv;
extern lv_obj_t * ui_txtBtnModusPv;
extern void ui_event_BtnModusMinPv(lv_event_t * e);
extern lv_obj_t * ui_BtnModusMinPv;
extern lv_obj_t * ui_txtBtnModusMinPv;
extern void ui_event_BtnModusPlan(lv_event_t * e);
extern lv_obj_t * ui_BtnModusPlan;
extern lv_obj_t * ui_txtBtnModusPlan;
extern void ui_event_BtnModusNow(lv_event_t * e);
extern lv_obj_t * ui_BtnModusNow;
extern lv_obj_t * ui_txtBtnModusNow;
extern void ui_event_BtnModusOff(lv_event_t * e);
extern lv_obj_t * ui_BtnModusOff;
extern lv_obj_t * ui_txtBtnModusOff;
extern lv_obj_t * ui_pnlSolar;
extern lv_obj_t * ui_barSolarGrid;
extern lv_obj_t * ui_barSolarPower;
extern lv_obj_t * ui_ImgSolar;
extern lv_obj_t * ui_ImgGrid;
extern lv_obj_t * ui_barGridPower;
extern lv_obj_t * ui_pnlDark;
extern lv_obj_t * ui_lblWifiWait;
extern lv_obj_t * ui_lblMqttWait;
extern lv_obj_t * ui_lblSolarPower;
extern lv_obj_t * ui_lblGridPower;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

