// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_MainScreen.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * animGridJump_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_evcc_logo_png);    // assets/evcc_logo.png
LV_IMG_DECLARE(ui_img_1529214255);    // assets/battery-2.png
LV_IMG_DECLARE(ui_img_955610505);    // assets/ev-charging-plug-icon.png
LV_IMG_DECLARE(ui_img_9025960_sun_icon_png);    // assets/9025960_sun_icon.png
LV_IMG_DECLARE(ui_img_1680447448);    // assets/electrical-tower-svgrepo-com.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
